### ISSUE TITLE
Menu search bar and logo 

### ISSUE THREAD

**Issue by xmilpa** [codarchlab/ariadne-portal#106]
The updated responsive menu search bar in subpages looks good in desktop view in Firefox. Chrome and IE differs from FF and pusches the underline down one pixel.
#95

**Comment by borsna** [comment]
Made a screendump in chrome Version 48.0.2564.109:
![image](https://cloud.githubusercontent.com/assets/794445/13006873/44342338-d18c-11e5-9c0d-ff87f1f187fb.png)

**Comment by janwieners** [comment]
Addendum: Search bar in navbar is completely out of place in IE.
