### ISSUE TITLE
Load more on filters in search results page keeps loading

### ISSUE THREAD

**Issue by eafiontzi** [codarchlab/ariadne-portal#108]
The error in the console says 

> TypeError: hash[1] is undefined

**Comment by scuy** [comment]
@eafiontzi: I could not exactly reproduce the bug but found something similar when loading more values in the period filter. The problem was caused by the different syntax needed for nested aggregations. Does my commit also fix your issue?

**Comment by eafiontzi** [comment]
Yeap, seems good! Thanks!

**Comment by eafiontzi** [comment]
Seems that the same bug appeared again
![image](https://cloud.githubusercontent.com/assets/14819444/13354880/59c9e4ce-dca6-11e5-9a90-d66011c56865.png)
