### ISSUE TITLE
Missing translations in search view

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#109]
<img width="854" alt="screen shot 2016-02-16 at 17 24 09" src="https://cloud.githubusercontent.com/assets/132811/13082720/2c0f17c4-d4d2-11e5-8f61-97f27768505a.png">

**Comment by eafiontzi** [comment]
I added the translations you are reffering to, though I do not see those elements for that specific resource 
![image](https://cloud.githubusercontent.com/assets/14819444/13104110/e147df18-d563-11e5-88e6-fd98a7508332.png)
