### ISSUE TITLE
Return from resource page leads to json response from elasticsearch

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#115]
When having used the timeline search and navigated to a resource and then go back with browser back button I get to a json response instead of search results. 

Problem for error searching is that it doesn't occur every time, but has happened for both Olof and I

**Comment by jfihn** [comment]
Another occation of this, now from map based search

![image](https://cloud.githubusercontent.com/assets/3796730/13391350/3bcc5bd4-ded4-11e5-9831-04c621aa239a.png)

**Comment by jfihn** [comment]
Please disregard from the chat to the left. :)

**Comment by scuy** [comment]
I am able to reproduce this every time when I go back in the history to the first page of a search result.
