### ISSUE TITLE
Error when trying to access resource on the web

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#122]
http://ariadne-portal.dcu.gr/page/18390516

**Comment by borsna** [comment]
Had a look at the data for the resource:
http://ariadne-portal.dcu.gr/data/18390516
Seems like the field is populated by the wrong data:

`landingPage: "title=anteprima dellimmagine; URL=http://www.catalogo.umbriacultura.it/samira/thumbs//operemusei/monte13400-sml.jpg",`

**Comment by eafiontzi** [comment]
It seems that  this is the way the original data are coded for this package and we will try to fix that in the mapping, before it comes to ES

**Comment by eafiontzi** [comment]
Fixed by republishing the package
