### ISSUE TITLE
Focus Europe in browse map

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#127]
At the moment, the world is shown several times (depending on the screen resolution).

Instead only Europe and the Mediterranean should be focused in the initial view.

**Comment by scuy** [comment]
The problem could be solved when the false outliers in the Indian Ocean are fixed in the catalog index.

**Comment by eafiontzi** [comment]
Sebastian you are correct, when I deleted the package with the wrong coordinates, focus was fixed. We are in touch with ADS to solve the coordinates issue.

**Comment by eafiontzi** [comment]
coordinates are now in place. It seems there are indeed some resources just outside Africa so I believe the focus is now correct

**Comment by scuy** [comment]
There are still some outliers that cause the broad focus in the intital map view.

I think the current implementation makes sense, but we should discuss the topic during the next user group meeting.

<img width="1236" alt="screen shot 2016-03-04 at 10 48 39" src="https://cloud.githubusercontent.com/assets/132811/13523623/e2349098-e1f6-11e5-9d7a-fd5784dd53b3.png">
