### ISSUE TITLE
Pieces of address in "Place" facet

### ISSUE THREAD

**Issue by Akillus** [codarchlab/ariadne-portal#128]
When clicking on the "Place" facet (left hand side of the interface) the place list shows some strange chops of addresses starting with a comma, like for instance:

 ", Via Castello, 39, 80070" (please note the comma at the beginning)

Is it due to metadata inconsistency or the interface use the comma to separate different fields?

**Comment by eafiontzi** [comment]
It is a metadata issue, we are looking into it

**Comment by eafiontzi** [comment]
Addresses do not start with a comma now, it was eliminated before inserting into ES
