### ISSUE TITLE
Visual bug with period facet 

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#139]
![image](https://cloud.githubusercontent.com/assets/3796730/13771707/11a26d40-ea90-11e5-83c5-003676efd895.png)

**Comment by jfihn** [comment]
Probably due to empty string in period name

**Comment by eafiontzi** [comment]
It is a data issue after all, we are working on that

**Comment by eafiontzi** [comment]
Cleared data from empty values
