### ISSUE TITLE
Missing translation for languages

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#140]
http://ariadne-portal.dcu.gr/page/18401584

resource.language.it

**Comment by borsna** [comment]
Found some other, complete list:
- [ ] resource.language.it
- [ ] resource.language.fr
- [ ] resource.language.nl
- [ ] resource.language.hu

**Comment by eafiontzi** [comment]
aba25ef1259916cc4ec904c51eb3236e603fea39
