### ISSUE TITLE
Error when clicking (i) on subjects from drop down suggestions on front page search

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#159]
For instance when searching for pottery and clicking for information on any of the auto suggestions. 

One example:
http://portal.ariadne-infrastructure.eu/subject/300108174

**Comment by borsna** [comment]
Seems like some of the subjects are missing. 
Other usbjects like http://portal.ariadne-infrastructure.eu/subject/300264092 loads like expected
