### ISSUE TITLE
Error when accessing a resource

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#165]
http://portal.ariadne-infrastructure.eu/search?q=23027394
http://portal.ariadne-infrastructure.eu/page/23027394

**Comment by jfihn** [comment]
More occurances: 
http://portal.ariadne-infrastructure.eu/page/23008216
http://portal.ariadne-infrastructure.eu/page/23009679

Seems to be something with the newly ingested DAI resources

**Comment by eafiontzi** [comment]
Seems that the resources are missing the element contributor-> name.
We will contact the provider to make the appropriate changes. 
In the meantime we will delete the package from the index to avoid error pages

**Comment by eafiontzi** [comment]
DAI resources are deleted and should be re-ingested
