### ISSUE TITLE
"Load more" second click

### ISSUE THREAD

**Issue by Akillus** [codarchlab/ariadne-portal#168]
When clicking for a second time the "Load more" link in the facet filters (e.g. on "Place" or "Publisher"), nothing happens and the user is "transported" on the top of the page.

Suggestion: it would maybe be useful to add a small "search + autocomplete" field on top of each facet to reduce the long lists of items appearing when the facet is opened and allow to people to go straight to what they are looking for ...

**Comment by eafiontzi** [comment]
I believe the first time the "Load more" button is clicked, we have all the rest of the relults, so maybe the issue actually is to hide the "Load more" button from the bottom when clicked.

**Comment by scuy** [comment]
I don't think that all facet values are always shown after the first click. Looking at the distribution of the values in native and derived subject indicates that there are probably a lot more values than the ones shown.
