### ISSUE TITLE
Search results: Pagination broken when using wildcards in query

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#17]
The asterisk gets URL-escaped, thereby destroying the original query string.

**Comment by borsna** [comment]
I can´t reproduce this localy with the current master branch checked out.
Is the code on http://ariadne-portal.dcu.gr up to date? 

**Atemt to reproduce**
Tried to search for `history*` on http://ariadne-portal.dcu.gr after pagination click: `/search?q=history%252A&page=2``

On localhost its escaped correctly after pagination click: `/search/?q=history%2A&page=2`

Is this reproducable on your local copy @scuy?

**Comment by scuy** [comment]
I am also not able to reproduce the error in my local version.

However I updated the version on http://ariadne-portal.dcu.gr and the error still persists.

Maybe it is an issue with the server configuration?

**Comment by borsna** [comment]
Fixed. Server did not return default UTF-8.
Changed config:

``` xml
 <Directory /var/www/ariadne-portal/public>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
                AddDefaultCharset UTF-8
</Directory>
```
