### ISSUE TITLE
AAT index: map prefLabels as nested documents

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#174]
In order to be able to only query for english terms (see #170), the prefLabels should be mapped as nested documents.

**Comment by eafiontzi** [comment]
If I understand correctly in the aat index we need this change to the mapping of the prefLabels element.
`
"prefLabels": {
                   "type" : "nested",
                    "properties": {
                        "label": {
                            "type":"string"                           
                         },                        
                        "lang": {
                            "type":"string"                            
                        }
                    }
                }
`
Is this the case?

**Comment by scuy** [comment]
Looks good.

2016-05-19 12:22 GMT+02:00 eafiontzi notifications@github.com:

**Comment by eafiontzi** [comment]
I have created a new index named aat_ariadne_v1 with the new mapping and copied the content from aat_ariadne. Should I change the alias now, or do you prefer to test it locally and make the appropriate changes sto that we have no errors in the live portal?

**Comment by scuy** [comment]
Seems to be working. I think it should be ok to change the alias.

**Comment by eafiontzi** [comment]
Ok, alias is in place :)
