### ISSUE TITLE
Resource landing page: Shorten long descriptions

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#18]
Long descriptions should be shortened to a few lines and be expandable with a "more" button.

**Comment by eafiontzi** [comment]
Done in 74322194be3c471cff92606fd0fd5cb8d5802adb. There was already a script on the page so I wrote there the extra lines, because as far as I can see "/public/js" is in .gitignore ;) . Unless someone wants to move the javascript code we can close the issue.

**Comment by eafiontzi** [comment]
fixed, but olof suggested using a library instead of jquery.
