### ISSUE TITLE
Different subject terms

### ISSUE THREAD

**Issue by hew503** [codarchlab/ariadne-portal#183]
On the homepage, in the search box drop-down we have the choices:

Native Subject 
ARIADNE Subject

When we look at search in list view we can choose to refine by:

Native Subject
Derived Subject

Should we make ARIADNE Subject and Derived Subject consistent? I think we talked about this in Oslo, and the plan was just to be explicit and use AAT Subject in both instances instead?

cheers

Holly

**Comment by jfihn** [comment]
Fixed in 1,2
