### ISSUE TITLE
basis of Tag Cloud index?

### ISSUE THREAD

**Issue by dstudhope** [codarchlab/ariadne-portal#188]
The  overall Tag Cloud (reached by What on initial screen) appears rather idiosyncratic in the terms displayed. 

Some terms are unexpected (but give results, eg "sec. V11 a.C.", "uncertain", "Road - class 3 togher") However these are not perhaps useful terms for a tag cloud?
Other terms do not appear to give results (eg "Archeologisch: bureauonderzoek")

The cloud must be based on an underlying index selected from the available possible indexes - it appears to be a mix of several indexes? What was the rationale for the current choice? Is it as intended?

Should it be restricted to AAT concepts perhaps plus some native subjects (as it is a WHAT index)?

Doug

**Comment by jfihn** [comment]
Change Tag Cloud to only use Derived Subject

**Comment by xmilpa** [comment]
TagCloud changed to use aggregation derivedSubject, only.
