### ISSUE TITLE
Ignore all entries with 0 as single year

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#197]

**Comment by eafiontzi** [comment]
I guess we ignore those elements that have BOTH from AND until with 0 value, but keep their periodName

**Comment by jfihn** [comment]
The idea is to remove entries with a 0 as both start and end year. See e.g. http://portal.ariadne-infrastructure.eu/page/13806829 or http://portal.ariadne-infrastructure.eu/data/13806754

According to Julian this has, most probably, been used instead of "unknown" year.

**Comment by jfihn** [comment]
And yes, if they have a periodName, that should remain.

**Comment by eafiontzi** [comment]
There are no records containing both temporal.from and temporal.until with zero values.
