### ISSUE TITLE
Browse View: Timeline (When)

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#24]
The timeline browse view should offer a way of navigating a search result or the whole catalog similar to the map browse view. It should display the distribution of resources in time and allow selecting a date range for starting or refining a search.

Similarly to the map view it should make use of aggregations that get refined when the user "zooms in".

<img width="1153" alt="screen shot 2015-11-16 at 17 01 48" src="https://cloud.githubusercontent.com/assets/132811/11186795/c3c7cc6a-8c83-11e5-814c-3d94bee97030.png">

**Comment by danielmarreirosdeoliveira** [comment]
![bildschirmfoto 2015-12-10 um 12 31 44](https://cloud.githubusercontent.com/assets/4498340/11714379/1e882fdc-9f3a-11e5-8ef3-2a352025b67d.png)

**Comment by danielmarreirosdeoliveira** [comment]
The photo shows the state of the implementation which was developed against a test dataset. The buckets contain doc_counts for resources with date_ranges reaching into or spanning over the buckets. 
If clicked any bucket will be expanded into 6 new buckets spanning the range from the buckets heading. 
This ticket will be closed and we will create new tickets for new feature requests based on the current state of implementation.
