### ISSUE TITLE
Browse view: Subjects (What)

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#25]
There should be a view that visualizes the distribution of different subjects in the catalog or a particular search result.

This view should include the AAT subjects, the languages and the data providers.

**Comment by borsna** [comment]
Do a tagcloud on the what landingpage.

**Comment by scuy** [comment]
Add some other facets:
- period names (temporal.periodName.raw)
- place names (spatial.placeName.raw)
- keywords (keyword.raw)

**Comment by xmilpa** [comment]
WordCloud now uses:
- derivedSubject.prefLabel.raw
- keyword.raw 
- spatial.placeName.raw
- temporal.periodName.raw
