### ISSUE TITLE
Subject landing page

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#26]
A separate view for displaying details about a single subject should be implemented.

<img width="1162" alt="screen shot 2015-11-16 at 17 09 00" src="https://cloud.githubusercontent.com/assets/132811/11187003/cb9dbd04-8c84-11e5-9021-196fad234a45.png">

**Comment by jfihn** [comment]
![image](https://cloud.githubusercontent.com/assets/3796730/12719276/5e10eae8-c8f4-11e5-9b03-5163066321ed.png)

Subject landing view

**Comment by scuy** [comment]
See #91

**Comment by jfihn** [comment]
Connected resources pose a problem as some concepts have thousands of resources connected to them and far from all of them have spatial information. Either we show them in some sort of list, but rather use the search function for doing that.

**Comment by scuy** [comment]
Maybe we can reuse the heatmap widget here?
