### ISSUE TITLE
Hierarchical query expansion based on AAT subjects

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#29]
Elasticsearch could be configured as described in Ceri Bindings paper "Implementing hierarchical semantic expansion in ARIADNE".

Another possibility would be enrich the data with ancestor concepts before ingest into elasticsearch in MoRe.

**Comment by scuy** [comment]
I will deliver a sample JSON.

**Comment by scuy** [comment]
I would suggest adding something like this:

``` json
{
    "archaeologicalResourceType": {
        "id": 1,
        "name": "Fieldwork archives"
    },

    ...

    "derivedSubject": [{
        "source": "http://vocab.getty.edu/aat/300007836",
        "prefLabel": "bridges (built works)"
    }, {
        "source": "http://vocab.getty.edu/aat/300006075",
        "prefLabel": "canals (waterways)"
    }],

    "broaderDerivedSubject": [{
        "source": "http://vocab.getty.edu/aat/300007835",
        "prefLabel": "transportation structures by form"
    }, {
        "source": "http://vocab.getty.edu/aat/300120693",
        "prefLabel": "transportation structures"
    }, {
        "source": "http://vocab.getty.edu/aat/300004894",
        "prefLabel": "single built works by function"
    }, {
        "source": "http://vocab.getty.edu/aat/300004795",
        "prefLabel": "single built works by specific type"
    }, {
        "source": "http://vocab.getty.edu/aat/300004790",
        "prefLabel": "single built works (built environment)"
    }, {
        "source": "http://vocab.getty.edu/aat/300264550",
        "prefLabel": "Built Environment (hierarchy name)"
    }, {
        "source": "http://vocab.getty.edu/aat/300264092",
        "prefLabel": "Objects Facet"
    }, {
        "source": "http://vocab.getty.edu/aat/300133792",
        "prefLabel": "artificial water channels"
    }, {
        "source": "http://vocab.getty.edu/aat/300006074",
        "prefLabel": "hydraulic structures by form"
    }, ... ],

    ...

    "providerId": "1104",
    "language": "en",
    "identifier": "http://registry.ariadne-infrastructure.eu/collection/11576804"
}
```

**Comment by scuy** [comment]
Does that make sense?

**Comment by eafiontzi** [comment]
Do you think it is sufficient to add an extra element in each resource (keep native and derived subject as well) that contains all alternate labels, broader labels and preflabels in different languages? For example:

```
"aatSubjects": [{
  "label": "貨船",
  "lang": "zh-hant"
 }, {
  "label": "huò chuán",
  "lang": "zh-latn-pinyin-x-hanyu"
 }, {
  "label": "barcos de carga",
  "lang": "es"
 }, {
  "label": "huo chuan",
  "lang": "zh-latn-pinyin-x-notone"
 }, {
  "label": "huo ch'uan",
  "lang": "zh-latn-wadegile"
 }, {
  "label": "vrachtschepen",
  "lang": "nl"
 }, {
  "label": "cargo vessels",
  "lang": "en"
 }, {
  "label": "ships, cargo",
  "lang": "en"
 }, {
  "label": "vrachtvaarders",
  "lang": "nl"
 }, {
  "label": "cargo boats",
  "lang": "en"
 }, {
  "label": "boats, cargo",
  "lang": "en"
 }, {
  "label": "buque de carga",
  "lang": "es"
 }, {
  "label": "vrachtboten",
  "lang": "nl"
 }, {
  "label": "cargo vessel",
  "lang": "en"
 }, {
  "label": "freighters",
  "lang": "en"
 }, {
  "label": "vessel, cargo",
  "lang": "en"
 }, {
  "label": "vrachtschip",
  "lang": "nl"
 }, {
  "label": "vessels, cargo",
  "lang": "en"
 }, {
  "label": "barco de carga",
  "lang": "es"
 }, {
  "label": "cargo ships",
  "lang": "en"
 }],
```

**Comment by scuy** [comment]
That should work. We need to be able to differentiate between labels that we display on the resource landing page and those that are only for search expansion. But if I understand you correctly this is the case, right?

**Comment by eafiontzi** [comment]
In the way suggested, each resource contains the native and derived subject like it used to, but we will include the extra aatSubjects element that contains all other labels (broader, alternate) flatly like in the example above for search purposes.

**Comment by eafiontzi** [comment]
Property "aatSubjects" covers the alternative labels

**Comment by scuy** [comment]
Check if the field is used in the portal search.

**Comment by scuy** [comment]
I can not see the field `aatSubjects` in the currently configured index `aat_ariadne`. Am I using the right index?

**Comment by eafiontzi** [comment]
The aatSubjects element is included in the catalog index, in each resource

**Comment by scuy** [comment]
Of course ... thanks.

**Comment by scuy** [comment]
When picking a subject from the suggestions in the search field we are currently using the subject ID as a query criterion because this is more precise than simple string matching.

In order to be able to make use of subject expansion we therefore need to include the subject IDs of the expanded (ancestor) subjects in the resource document as well.

**Comment by scuy** [comment]
The parameter `subjectUri` currently maps to the elasticsearch field `derivedSubject.source` instead it should be translated to a newly created field `aatSubjects.source`.

**Comment by eafiontzi** [comment]
Ok, if I understand correctly, you are suggesting adding an extra element inside aatSubjects, named source, with the corresponding value of the aat url. That would require the appropriate mapping of the raw field I guess, which would lead to the publishing of all records once more, which I believe is quite time consuming.

Do you think we could use instead of subjectUri the subjectLabel (from aat_ariadne index the element prefLabel) and match it with aatSubjects.label? Or this would make the query slower?

**Comment by scuy** [comment]
The problem is that there might be different concepts with similar labels. Ceri and Doug pointed out this need for disambiguation in several of the technical meetings. So I think we should try to do the matching based on the URI if that is possible.

**Comment by eafiontzi** [comment]
I see. Do you think it would be ok instead of adding the whole URI (for instance http://vocab.getty.edu/aat/300391496), to add just the AAT ID (which is the last part of the URI, for instance 300391496), so that there would be no need for extra raw values and new index?

As far as I can see in the link you sent yesterday (http://portal.ariadne-infrastructure.eu/search?q=*&subjectUri=300232815&subjectLabel=transport%20vessels), the id is used as subjectUri, so there should be no problem.

**Comment by scuy** [comment]
Yes, that should work.

**Comment by eafiontzi** [comment]
Great, I will proceed with that then ;)

**Comment by eafiontzi** [comment]
The element aatSubjects.id has been added to the index, and all packages including AAT terms have been republished
