### ISSUE TITLE
Map on resource landing page contains marker for source resource

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#3]
Auf Basis der location der angezeigten Resource wird eine geo distance gefilterte Query ausgeführt,
die die umliegenden Objekte aufliststet. Unter diesen befindet sich auch die location der originalen Resource, was derzeit nicht auffällt, da die originale
Resource später gezeichnet und Orange markiert wird.

**Comment by borsna** [comment]
Is this issue still relevant when we have a new color on the current marker introduces in #55?

**Comment by danielmarreirosdeoliveira** [comment]
Its a really tiny issue. The nearby resources contain also the original resource, but since the original resource is rendered separately and at last again (the red one) the other one is not hidden. Its rather cosmetic at the moment, but could probably confuse a developer later.
