### ISSUE TITLE
Welcome Page: Include links to browse views

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#30]
As depicted in the mockups (v4) the welcome page should feature the links to the three browse sections (where, when, what).

![screen shot 2015-11-30 at 13 39 22](https://cloud.githubusercontent.com/assets/132811/11471734/cda33118-9767-11e5-8b92-0ef147a9cb1a.png)

**Comment by eafiontzi** [comment]
closed in 9d8f7678883f8f5e041d17c53a28ce762a8cc580. We should add the link to the other sections when they are ready
