### ISSUE TITLE
Welcome Page: Box for textual content

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#31]
As depicted in the mockups (v4) the welcome page should feature a box that includes a short project description.

![screen shot 2015-11-30 at 13 39 22](https://cloud.githubusercontent.com/assets/132811/11471754/fdda7cec-9767-11e5-8c2a-e0d7fe36e54a.png)

**Comment by eafiontzi** [comment]
closed with ba995ef536f1b48b2daae38ec5e2ec2ab1cd448a
