### ISSUE TITLE
Search bar: Dropdown list for field

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#32]
As depicted in the mockups (v4) the search bar should feature a dropdown list for selecting the field the user wants to query.

![screen shot 2015-11-30 at 13 44 21](https://cloud.githubusercontent.com/assets/132811/11471834/84e4d58e-9768-11e5-81fe-2845b7af7341.png)

**Comment by borsna** [comment]
The function is implemented but i cant quite get the width of the search-box to work.
Can someone give it a try? ping @scuy @eafiontzi

**Comment by borsna** [comment]
@jfihn have fond a nice fix! tnx!
