### ISSUE TITLE
Icons for archaeological resource types

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#35]
List of types to make icons for:
- [x] Fieldwork archives
- [x] Event/Intervention resources
- [x] Sites and monuments databases or inventories
- [x] Scientific datasets
- [x] Artefact databases or image collections
- [x] Burial databases

**Comment by borsna** [comment]
First draft of the icons `50x50px`
All of these are combined icons from glyphicons.com
Suggestions for different symbols are welcome

**Fieldwork archives**
![fieldwork_archives](https://cloud.githubusercontent.com/assets/794445/12850663/296f994e-cc26-11e5-8ae6-1a2936fadeae.png)

**Event/Intervention resources**
![event_intervention_resources](https://cloud.githubusercontent.com/assets/794445/12850669/2f77f0de-cc26-11e5-88d1-733b15000612.png)

**Sites and monuments databases or inventories**
![sites_and_monuments_databases_or_inventories](https://cloud.githubusercontent.com/assets/794445/12850680/3958e69e-cc26-11e5-86db-50736b7b022e.png)

**Scientific datasets**
![scientific_datasets](https://cloud.githubusercontent.com/assets/794445/12850681/3e1f29fe-cc26-11e5-92b1-3cee9a79ba9b.png)

**Artefact databases or image collections**
![artefact_databases_or_image_collections](https://cloud.githubusercontent.com/assets/794445/12850682/43b96d02-cc26-11e5-9d55-d4e37a75eac7.png)

**Burial databases**
![burial_databases](https://cloud.githubusercontent.com/assets/794445/12850686/48a5ffe2-cc26-11e5-8166-ba023e7dd236.png)
