### ISSUE TITLE
Navigation: "Catalog" should point to welcome page

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#41]
Since we will have links to the different browse sections on the welcome page the link "Catalog" should point to the welcome page.

The Ariadne logo in the navigation bar should point to http://www.ariadne-infrastructure.eu/ .

**Comment by eafiontzi** [comment]
In ba995ef536f1b48b2daae38ec5e2ec2ab1cd448a I linked the Ariadne logo to http://www.ariadne-infrastructure.eu. I was working on that file at the time, hope that does not causes a problem

**Comment by janwieners** [comment]
No problem! However, I unlinked the logo on the front page, hope that's ok for you.
