### ISSUE TITLE
Welcome page: Make boxes responsive

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#42]
On my screen the images in the "browse" box stack. They should scale with the resolution.

<img width="1219" alt="screen shot 2015-12-02 at 15 44 29" src="https://cloud.githubusercontent.com/assets/132811/11533814/ea982198-990b-11e5-8544-c01e9c070530.png">

**Comment by eafiontzi** [comment]
Seems ok now 236460bf42fed803ad42a45e367751fda7857a93. Could you check it and close it you think it is ok? ;)
