### ISSUE TITLE
Hide types, make resource types more prominent

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#5]
As discussed at the meeting in Vienna resource types should be the prominent category in the portal interface.

This means that the resource type should be the topmost facet and should also be the basis for the icons in the search result view.

The current types are technical details that should be hidden from the user.

**Comment by eafiontzi** [comment]
In the last commit (4f5132868124dce9d8c2de8a3c74e04c82669372) I changed the search results next to the badge type to show archeologicalResourceType. 

What about the resource type being the topmost facet? I see in #13 that we closed all other facets except for type, we still want resource type above the open facet type?

**Comment by scuy** [comment]
I think it was decided that the type should be hidden from user completely. So I would suggest removing the type facet and making resource type the topmost and opened facet.

**Comment by eafiontzi** [comment]
Ok, sounds good, should we close this issue and asign a new one?

**Comment by scuy** [comment]
I have to refactor resource type handling in #47 anyway, so I will thereby also remove the type facet.
