### ISSUE TITLE
Uncaught TypeError: $(...).readmore is not a function

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#51]
For example when opening /resource/11637896 my javascript console shows

```
Uncaught TypeError: $(...).readmore is not a function
```

This also seems to prevent the map under geographically similar from loading.

**Comment by borsna** [comment]
I think this occurs if `gulp` was not succesfull and the library is missing.

**Comment by jfihn** [comment]
A 'bower install' should fix this problem

**Comment by scuy** [comment]
oops ... sure ... thanks!

**Comment by borsna** [comment]
Easy to forget :)

**Comment by fawzyeltop** [comment]
### 

> [`__`](

- 

- [ ] @ #1. url

)
