### ISSUE TITLE
Better error pages

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#53]
Custom error pages can be placed in resources/views/errors/

**Comment by eafiontzi** [comment]
Fixed 404 in 470c341bd3b083f505658a093e6dc7857ea242c3
Do you have other errors in mind?

**Comment by scuy** [comment]
Also add a generic error page with a contact email that can be configured.

**Comment by eafiontzi** [comment]
Seperate pages for 404, 500 and bad query, generic page for all other exceptions.
Email report is being sent every time an exception occurs.
Must configure project email
