### ISSUE TITLE
Use random background image for the frontpage

### ISSUE THREAD

**Issue by borsna** [codarchlab/ariadne-portal#57]
Set random image from Elizabeth Fentress collection as the background image on the frontpage.
Also include a footer with the information about the source (wikimedia licence).

**Comment by janwieners** [comment]
Good idea! Where can I find those images / the Elizabeth Fentress collection?

**Comment by scuy** [comment]
https://app.box.com/s/96v4dt98nddo6vyixjyhe49d9o3z6rrr

**Comment by janwieners** [comment]
Merci!

**Comment by janwieners** [comment]
Hm, what about changing the background image on the front page after ~5 seconds by fading one image out and another image in?

**Comment by borsna** [comment]
I think it wold look nice :+1: 
But it could be a bit heavy network traffic for eg mobiles?
