### ISSUE TITLE
No Labels for nearby resources on small map on resource page

### ISSUE THREAD

**Issue by danielmarreirosdeoliveira** [codarchlab/ariadne-portal#60]
For example the nearby resources on that route: /page/11637828 show now label.
That there is no placeName set seems to be a valid case, judging from the code in map.js,
which renders the heatmap. However, taking the code snippet from there which then sets the label to "[lat], [lon]", clicking on any of the items on the given page results in a search with no hits.

**Comment by scuy** [comment]
I created issue #61 for the empty result when clicking on a marker with no place name in the browse map.
