### ISSUE TITLE
Can´t load browse/when

### ISSUE THREAD

**Issue by borsna** [codarchlab/ariadne-portal#64]
Does not work on my local install or the protal http://ariadne-portal.dcu.gr/browse/when
Message in console:

```
Uncaught TypeError: Cannot read property 'buckets' of undefinedBucketTimeline.redraw 
@ bucket-timeline.js:111(anonymous function) 
@ bucket-timeline.js:127fire 
@ jquery.js:3099self.fireWith 
@ jquery.js:3211done 
@ jquery.js:8264(anonymous function) 
@ jquery.js:8605
```

Is all libraries included?

**Comment by danielmarreirosdeoliveira** [comment]
The search result is empty with the current index (the route was developed against a test one), and there is no error handling for that. So there should be some sort of message indicating it, at least on the javascript console.

**Comment by borsna** [comment]
Perhaps just some simple error message for directly in the body?

``` javascript
...
$(".container-fluid .fullscreen").html('Error loading: ' + e.message);
...
```

**Comment by danielmarreirosdeoliveira** [comment]
Yes, could be something like this.
It should indicate that no data could be found in the index,
because that is why the 'buckets' are empty in javascript.

**Comment by danielmarreirosdeoliveira** [comment]
Resolved with commit https://github.com/codarchlab/ariadne-portal/commit/7e96cc18b2c4622dc748a68a40325115b5499ca1 since the data from the index can be used now to populate the timeline.
