### ISSUE TITLE
Update welcome page images

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#66]
> Dear Johan,
> The portal images on box.net are now all at more or less 1600. They are all either mine or from sources like wikipedia, wikimedia commons and Flikr creative commons, however, I am not sure how the attribution works. Will supply if you let me know
> all best
> Lisa

**Comment by borsna** [comment]
Related to #63

**Comment by eafiontzi** [comment]
Closed in 41d0722c4c17d8b44d592696be68bba13eb59290
