### ISSUE TITLE
Better formating of higlights in search results

### ISSUE THREAD

**Issue by borsna** [codarchlab/ariadne-portal#75]
Use configured labels for all highlights in search results.

![highlights](https://cloud.githubusercontent.com/assets/794445/12678011/dae39fc0-c69c-11e5-9a2b-ecd5bfdf6082.png)

**Comment by eafiontzi** [comment]
I had a few corrected, hope to have caught them all in 714bad751bc1d82941197a718600a2ed96a7f6aa

**Comment by borsna** [comment]
looks good :+1:

**Comment by eafiontzi** [comment]
Some translations missing
![image](https://cloud.githubusercontent.com/assets/14819444/13286086/89cfa14a-db07-11e5-8ec9-597ed4bf7677.png)
