### ISSUE TITLE
Map: Make button for showing resources within current area more intuitive

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#79]
Comment from user group. Button on map for showing resources in current map area is not perfect in regards to intuitivity. Check for options to icon or add text.

**Comment by scuy** [comment]
Maybe the refresh icon (same as in the box for adjusting the query string above) would make more sense?

**Comment by jfihn** [comment]
I've changed the button to search icon (magnifying glass). We already have a refresh icon for when map changes and resources are refreshing so it didn't work well with that icon. Any comments on this or any other suggestions on how to make this clearer?

**Comment by eafiontzi** [comment]
I think it is quite clearer now. Maybe we should wait until the next user group meeting and see what the users think ;)
