### ISSUE TITLE
Create a robots.txt

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#8]
Until public announcement no page of the portal should be indexed by search engines.

**Comment by scuy** [comment]
Also delete existing entries for the portal from the google index.

**Comment by borsna** [comment]
`<meta name="robots" content="noindex">` until we have release it

**Comment by borsna** [comment]
I have commited a fix for this (rendering `<meta name="robots" content="noindex">` if `APP_ENV` is `local` or `staging`).

If we want to remove the current pages from e.g. the goole search index we need to verify the site in google wemaster tools (via google analytics or tracking a google site verification).

Should we create a new task to add config for google analytics and close this one?

**Comment by scuy** [comment]
I created the follow-up tickets #36 and #38.

**Comment by borsna** [comment]
Great! i think it´s enough to get a google analytics tracking in there and us the same key to verify against google webmaster tools.
