### ISSUE TITLE
Some way to expand filters to show more options than 10

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#80]
Comment from user group. 

Use case:
Semantic location – the geographic area can be specified by entering a geographic name and optionally a range.

In use case group we decided that current solution with free text in combination with filters is enough for this use case, but we might need a possibility to show all options in a filter in a list, perhaps on another page.

**Comment by borsna** [comment]
Load more link if current result set have > 10 buckets is done via a ajax call (the filter is re-rendered with 100 buckets instead of default 10)
![load-more](https://cloud.githubusercontent.com/assets/794445/12848645/7cdf868a-cc1b-11e5-8fbb-91582acf7621.png)
