### ISSUE TITLE
Map showing results not in result list

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#86]
http://ariadne-portal.dcu.gr/search?q=Motala+kommun

**Comment by scuy** [comment]
(Resource 14209366)[http://ariadne-portal.dcu.gr/page/14209366] correctly seems to be among the results. This would mean that this is not a bug, right?

**Comment by jfihn** [comment]
Sorry. Not a bug. Confused by the off-centering of the map
