### ISSUE TITLE
General function for adding tooltips

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#87]

**Comment by scuy** [comment]
Tooltips should be added for:
- [ ] refresh button in filter map (see #79)
- [ ] refresh button next to current search query
- [ ] export button / file icon on resource landing page
- [ ] link button on resource landing page

**Comment by eafiontzi** [comment]
Cases mentioned above are covered,
Reopened if any new places for tooltips comes to mind or labels need changing
