### ISSUE TITLE
Add type "nested" to temporal in elasticsearch mapping

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#96]
In order to be able to implement a meaningful timeline visualization the elasticsearch mapping has to be updated. The mapping for the field `temporal` has to be changed to the following:

``` JSON
 "temporal": {
                      "type" : "nested",
                      "properties": {
                      ...
```

**Comment by eafiontzi** [comment]
Mapping contains type nested for temporal elements
